### ISSUE TITLE
backgroundColor parameter is ignored, background is always white

### ISSUE THREAD

**Issue by skoften** [hansemannn/Ti.WKWebView#3]
In the default webView we can set the backgroundColor property:

<img width="470" alt="screen shot 2017-02-06 at 20 43 23" src="https://cloud.githubusercontent.com/assets/1286410/22663570/5e9e39c4-ecad-11e6-8ab8-89a8bce1e125.png">

But with Ti.WKWebView it's always white:

<img width="495" alt="screen shot 2017-02-06 at 20 44 24" src="https://cloud.githubusercontent.com/assets/1286410/22663591/7218922e-ecad-11e6-870c-64a13b1947e0.png">

Also, the loadingIndicator is missing, would be nice to have that :-)

**Comment by hansemannn** [comment]
The background-color should be set in the HTML document. But I'll leave it open for an improvement in future versions.

**Comment by skoften** [comment]
Yes I understand, I also have it set at the html document, but there's always a ugly white flash before the page is loaded, depending on how quick the page is loaded...

Thanks!

**Comment by hansemannn** [comment]
Here we go: https://github.com/hansemannn/Ti.WKWebView/releases/tag/v1.2.0
