### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by skoften** [hansemannn/Ti.WKWebView#4]
I've implemeted the WKWeView in our live app last week, but had to replace it again with the normal webview. Reason: content isn't rendered correctly.

We use the webviews to show html5 videos. Just plain html5 from a remote page, but also Youtube and our own JWplayer (html5). After some days testing we've noticed it wasn't just a incident; the content isn't rendered correctly, but it happens randomly. Sometimes after reloading it works, but especially when there are multiple webview added in a tableView, things aren't looking good.

Some screenshots;

![img_0017](https://cloud.githubusercontent.com/assets/1286410/23154554/c04726c4-f80e-11e6-90a6-d84772901955.PNG)

<img width="433" alt="screen shot 2017-02-10 at 14 36 55" src="https://cloud.githubusercontent.com/assets/1286410/23154564/d2bd3866-f80e-11e6-81c3-55f0bbfcf760.png">

![img_0352](https://cloud.githubusercontent.com/assets/1286410/23154587/eb7a251c-f80e-11e6-8a8b-9cb2396c238c.PNG)

As you can see the view sometimes stays black. If you click it, the Youtube video starts to play (fullsceen, which is normal behaviour). But most of the time the play button doesn't appear or other elements are gone.

Building with SDK6.0.1.GA and 6.0.2xxxx on OSX.

**Comment by hansemannn** [comment]
Has to be a WKWebView issue - I don't do more than setting the remote URL. Ensure that your ATS-settings allow all webview sources (`NSAllowsArbitraryLoadsInWebContent` and `NSRequiresCertificateTransparency`).

**Comment by skoften** [comment]
Thanks for the reply. Can I configure these settings in the JS layer, or should a change that in the native module before building?

**Comment by hansemannn** [comment]
Could *could* probably expose them on the JS-side and access the JS-variable with 
```js
webView.evalJS('yourVar', function(e) {
    alert(e.result);
});
```
Closing this issue to wait until the [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=140191) is resolved.
